// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PinjamRuang.Data;

#nullable disable

namespace PinjamRuang.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214140857_FixBorrowingTanggal")]
    partial class FixBorrowingTanggal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PinjamRuang.Entities.Borrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Keperluan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("pending");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Borrowings");
                });

            modelBuilder.Entity("PinjamRuang.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 40,
                            CreatedAt = new DateTime(2026, 2, 14, 14, 8, 54, 638, DateTimeKind.Utc).AddTicks(2616),
                            Description = "Ruang kelas lantai 1",
                            Location = "Gedung A",
                            Name = "Ruang A101",
                            Status = "available",
                            UpdatedAt = new DateTime(2026, 2, 14, 14, 8, 54, 638, DateTimeKind.Utc).AddTicks(2617)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 2, 14, 14, 8, 54, 638, DateTimeKind.Utc).AddTicks(2623),
                            Description = "Ruang rapat",
                            Location = "Gedung B",
                            Name = "Ruang B202",
                            Status = "available",
                            UpdatedAt = new DateTime(2026, 2, 14, 14, 8, 54, 638, DateTimeKind.Utc).AddTicks(2624)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 200,
                            CreatedAt = new DateTime(2026, 2, 14, 14, 8, 54, 638, DateTimeKind.Utc).AddTicks(2627),
                            Description = "Untuk acara besar",
                            Location = "Gedung Serbaguna",
                            Name = "Aula Utama",
                            Status = "unavailable",
                            UpdatedAt = new DateTime(2026, 2, 14, 14, 8, 54, 638, DateTimeKind.Utc).AddTicks(2628)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 25,
                            CreatedAt = new DateTime(2026, 2, 14, 14, 8, 54, 638, DateTimeKind.Utc).AddTicks(2630),
                            Location = "Gedung C",
                            Name = "Lab Komputer 1",
                            Status = "available",
                            UpdatedAt = new DateTime(2026, 2, 14, 14, 8, 54, 638, DateTimeKind.Utc).AddTicks(2630)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 35,
                            CreatedAt = new DateTime(2026, 2, 14, 14, 8, 54, 638, DateTimeKind.Utc).AddTicks(2632),
                            Location = "Gedung D",
                            Name = "Ruang D303",
                            Status = "available",
                            UpdatedAt = new DateTime(2026, 2, 14, 14, 8, 54, 638, DateTimeKind.Utc).AddTicks(2632)
                        });
                });

            modelBuilder.Entity("PinjamRuang.Entities.Borrowing", b =>
                {
                    b.HasOne("PinjamRuang.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
