// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PinjamRuang.Data;

#nullable disable

namespace PinjamRuang.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210104556_CreateTableRoom")]
    partial class CreateTableRoom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PinjamRuang.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 40,
                            CreatedAt = new DateTime(2026, 2, 10, 10, 45, 53, 41, DateTimeKind.Utc).AddTicks(5606),
                            Description = "Ruang kelas lantai 1",
                            Location = "Gedung A",
                            Name = "Ruang A101",
                            Status = "available",
                            UpdatedAt = new DateTime(2026, 2, 10, 10, 45, 53, 41, DateTimeKind.Utc).AddTicks(5610)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 2, 10, 10, 45, 53, 41, DateTimeKind.Utc).AddTicks(5616),
                            Description = "Ruang rapat",
                            Location = "Gedung B",
                            Name = "Ruang B202",
                            Status = "available",
                            UpdatedAt = new DateTime(2026, 2, 10, 10, 45, 53, 41, DateTimeKind.Utc).AddTicks(5616)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 200,
                            CreatedAt = new DateTime(2026, 2, 10, 10, 45, 53, 41, DateTimeKind.Utc).AddTicks(5618),
                            Description = "Untuk acara besar",
                            Location = "Gedung Serbaguna",
                            Name = "Aula Utama",
                            Status = "unavailable",
                            UpdatedAt = new DateTime(2026, 2, 10, 10, 45, 53, 41, DateTimeKind.Utc).AddTicks(5619)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 25,
                            CreatedAt = new DateTime(2026, 2, 10, 10, 45, 53, 41, DateTimeKind.Utc).AddTicks(5621),
                            Location = "Gedung C",
                            Name = "Lab Komputer 1",
                            Status = "available",
                            UpdatedAt = new DateTime(2026, 2, 10, 10, 45, 53, 41, DateTimeKind.Utc).AddTicks(5621)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 35,
                            CreatedAt = new DateTime(2026, 2, 10, 10, 45, 53, 41, DateTimeKind.Utc).AddTicks(5623),
                            Location = "Gedung D",
                            Name = "Ruang D303",
                            Status = "available",
                            UpdatedAt = new DateTime(2026, 2, 10, 10, 45, 53, 41, DateTimeKind.Utc).AddTicks(5623)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
